version: "3.8"

services:
  temporal-ui:
    image: temporalio/ui:2.14.0
    ports:
      - "8233:8233" # UI port
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233 # assumes Temporal is running locally on host
