global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "temporal"
    static_configs:
      - targets: ["temporal:8001"] # Server-side Temporal metrics

  - job_name: "temporal-worker"
    static_configs:
      - targets: ["host.docker.internal:9464"] # Node.js worker metrics

remote_write:
  - url: ""
    basic_auth:
      username:
      password:
